name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: '11' # Use the Java version that matches your project

    - name: Build with Leiningen
      working-directory: ./mermaid-workflow-api
      run: lein uberjar 

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: mermaid-workflow-api # Your Azure App Service name
        publish-profile: ${{ secrets.AZURE_WEBAPPAPI_PUBLISH_PROFILE }}
        package: ./mermaid-worflow-api/target/*-standalone.jar # The path to your built artifact
